language: generic
jobs:
  include:
    - script: echo "Starting Build $TRAVIS_BUILD_NUMBER"
    - stage: GitHub Release
      script: skip
      deploy:
        provider: releases
        api_key: $github_api
        skip_cleanup: true
        on:
          tags: true
