language: generic
jobs:
  include:
    - script: echo "Starting Build $TRAVIS_BUILD_NUMBER"
    - stage: GitHub Release
      script: skip
      deploy:
        provider: releases
        api_key: "625e77852b9667c0d704ae81c28a426e5bf65128"
        skip_cleanup: true
        on:
          tags: true
